### ISSUE TITLE
You contact details

### ISSUE THREAD

**Issue by samuelimoisili** [Federico-abss/CS50-intro-course#1]
I would need your email address I have an issue with the CS50 solution

**Comment by BrendanC-2288** [comment]
Hi, Who are you though and what is this concerning?

**Comment by brendanc2122** [comment]
> I would need your email address I have an issue with the CS50 solution

Hi, Who are you though and what is this concerning?

**Comment by Federico-abss** [comment]
I am the owner of the original repo, what's up?
Inviato da Yahoo Mail su Android 
 
  Il gio, 26 mar, 2020 alle 10:43, BrendanC-2288<notifications@github.com> ha scritto:   



I would need your email address I have an issue with the CS50 solution


Hi, Who are you though and what is this concerning?

**Comment by Federico-abss** [comment]
> I would need your email address I have an issue with the CS50 solution

I am the owner of the repo, you can write me at federicomannucci@yahoo.it

**Comment by brendanc2122** [comment]
> > I would need your email address I have an issue with the CS50 solution
> 
> I am the owner of the repo, you can write me at [federicomannucci@yahoo.it](mailto:federicomannucci@yahoo.it)

I recognise that you're the owner but who is alium0978 and why am I being asked for my email address because he has an issue

**Comment by Federico-abss** [comment]
> I recognise that you're the owner but who is alium0978 and why am I being asked for my email address because he has an issue

I have no idea why you are involved, just ignore this
