### ISSUE TITLE
How did your limit function pass check50?

### ISSUE THREAD

**Issue by purple-mustache** [Federico-abss/CS50-intro-course#4]
Did you have to declare your <limit()> function in any of the others files before it passed check50? I created a function and it compiles with "make" but not with check50.

**Comment by ywl2001** [comment]
I didn't use limit function. What do you mean by that? Sorry, I'm not the
natives...

**Comment by purple-mustache** [comment]
> Did you have to declare your <limit()> function in any of the others files before it passed check50? I created a function and it compiles with "make" but not with check50.

by limit function, I mean 'int limit(int RGB)' that you said you created to stop repetitions in sepia

**Comment by Federico-abss** [comment]
Since it is used only in the files it was defined in as a sort of helper function it does not need to be put in header files

**Comment by purple-mustache** [comment]
thank you
